# GMGT Usage

This notebook illustrates the data structure and usage of the GMGT dataset(s).
Please have a look at the `README` file in this repo for downloading the data and installing the package
(or copying the `gmgt.py` file in your code).

This Notebook assumes that - regardless of your environment (Python module, Notebook) - you have all requirements installed (including jupyterlab: `pip install jupyterlab`) and that you can import the `get_records` function as follows:

In [29]:
from gmgt import get_records

In this Notebook we will use one of the four datasets currently implemented:

 - `esm.hdf` (Engeneering Strong motion dataset)
 - `kik.hdf` (Kik-NET dataset)
 - `knet.hdf` (K-NnET dataset)
 - `ngawest2.hdf` (NGA West 2 dataset)

Assuming you downloaded the datasets in a specific directory (change the path below in your code accordingly):

In [30]:
import os
file_path = os.path.join(os.path.expanduser('~'), 'Nextcloud', 'gmgt', 'datasets', 'esm.hdf')

## Record structure

For illustrative purposes only (the code below is quite useless in normal processing), let us analyze the content of the `get_records` function, which yields records from the dataset

In [31]:
for h1, h2, v, dt, meta in get_records(
    file_path,
    min_magnitude=7.5,  # only records with at least magnitude 7.5
    available_components=['HH', 'HHV'],  # only records with at least the two horizontal components
    missing_magnitude=False  # magnitude must be given (this should always be the case)
    # you can add here any metadata field,
    # optionally prefixed with min_ max_ or missing_
):
    print(f'1st horizontal component (m/s^2, numpy array):\n{h1}\n')
    print(f'2nd horizontal component (m/s^2, numpy array):\n{h2}\n')
    print(f'vertical component (m/s^2, numpy array):\n{v}\n')
    print(f'dt (numpy float):\n{dt}\n')
    print(f'metadata (namedtuple):\n{meta}\n')
    
    # exit the loop, we want just to show the first record structure
    break

1st horizontal component (m/s^2, numpy array):
[1.036e-05 2.071e-05 2.070e-05 ... 2.145e-05 2.144e-05 2.143e-05]

2nd horizontal component (m/s^2, numpy array):
[1.350e-06 2.690e-06 2.700e-06 ... 1.417e-05 1.418e-05 1.418e-05]

vertical component (m/s^2, numpy array):
[-2.460e-05 -4.919e-05 -4.919e-05 ...  6.460e-05  6.461e-05  6.461e-05]

dt (numpy float):
0.005

metadata (namedtuple):
metadata(id=27, epicentral_distance=269.8, rupture_distance=nan, rupture_distance2=nan, joyner_boore_distance=nan, joyner_boore_distance2=nan, hypocentral_distance=269.98525885684944, fault_normal_distance=nan, fault_parallel_distance=nan, event_id='INT-20230206_0000222', origin_time=Timestamp('2023-02-06 10:24:49'), origin_time_resolution='s', event_latitude=38.11, event_longitude=37.24, magnitude=7.5, magnitude_type='Mw', event_depth=10.0, depth_to_top_of_fault_rupture=nan, fault_rupture_width=nan, dip=nan, dip2=nan, rake=nan, rake2=nan, strike=nan, strike2=nan, fault_type='Strike-Slip', station_id='T

The variable `meta` (arbitrary name, you can change it in your code) denotes the record metadata.
It can can be seen as a row of the table representing the full dataset medatada.
Note that you can access the record fields (table columns) as normal Python attributes. For instance:

In [32]:
meta.magnitude

7.5

For more details, see [here](https://github.com/rizac/gmgt-collect/blob/main/metadata_fields.yml).

## Function `get_records`

The [previous link](https://github.com/rizac/gmgt-collect/blob/main/metadata_fields.yml) also illustrates the metadata fields that you can pass to the `get_records` function.

The function accepts a HDF file path (mandatory) and then yields records according to optional arguments
provided as <field>=value pairs, returning only metadata rows (and relative waveforms) that match all specified conditions.
Optional arguments such as min_<field>, max_<field>, or missing_<field>
can be used to filter values below, above, or those that are missing / N/A.

For more details on `get_records` function, you can inspect its docstring in the Python module `gmgt.py`, or alternatively type:

In [33]:
help(get_records)

Help on function get_records in module gmgt:

get_records(dataset_path, **filters) -> collections.abc.Iterator[tuple[numpy.ndarray, numpy.ndarray, numpy.ndarray, float, tuple]]
    Yield datasets records in the form:
    
    (h1, h2, v, dt, metadata)
    
    where:
    - h1, h2 and v are numpy arrays denoting the time histories, in m/s^2. h1 and h2
      denote the two horizontal components and v the vertical. An empty array indicates
      that the component is not available. The two horizontal components do not have
      further information (e.g., orientation such as north-south is not available).
    - dt is the float denoting the data sampling interval (in s)
    - metadata is a namedtuple, and it is quite self-explanatory (you can access all
      metadata fields as normal attributes, e.g. `metadata.magnitude`. For a full list
      of fields, see:
      <https://github.com/rizac/gmgt-collect/blob/main/metadata_fields.yml>
    
    :param dataset_path: a string denoting the dat

## Basic plotting

Plotting data should be done with care, as the code might hang for several hundreds of thousand of points.
As such, in the following example we focus only on high magnitudes, showing how to plot metadata and data

In [ ]:
magnitudes = []
distances = []
for h1, h2, v, dt, meta in get_records(
    file_path,
    min_magnitude=6,  # only records with at least magnitude 7.5
    max_epicentral_distance=600, # only records within 600 km
    available_components=['HH', 'HHV']  # only records with at least the two horizontal components
):
    magnitudes.append(meta.magnitude)
    distances.append(meta.epicentral_distance)

from matplotlib import pyplot as plt
plt.scatter(distances, magnitudes)
plt.title('Records with magnitude > 6 (ESM dataset)')
plt.xlabel('epicentral distance (km)')
plt.ylabel('magnitude')
plt.show()

import numpy as np

plt.plot(np.arange(len(h1)) * dt, h1)
plt.title('Last read record (first horizontal component)')
plt.xlabel('time (s)')
plt.ylabel('A (m/s^2)')
plt.show()

plt.plot(np.arange(len(h1)) * dt, h2)
plt.title('Last read record (second horizontal component)')
plt.xlabel('time (s)')
plt.ylabel('A (m/s^2)')
plt.show()

plt.plot(np.arange(len(h1)) * dt, v)
plt.title('Last read record (vertical component)')
plt.xlabel('time (s)')
plt.ylabel('A (m/s^2)')
plt.show()

